version: '3.9'

services:
  dude_path_database:
    image: mysql:8.0
    container_name: dude_path_database
    environment:
      - MYSQL_DATABASE=dude_path_database
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=myroot12345
    ports:
      - "3307:3306"

  dude_path_api:
    build: ./app/api/
    container_name: dude_path_api
    # volumes:    # (Why this breaking my container).
    #   - ./app/api:/code
    ports:
      - "23000:23000"

