version: '3.9'

networks:
  dude_path_network:

services:
  dude_path_database:
    image: postgres:alpine
    container_name: dude_path_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dude_path_database
    volumes:  # executing the sql file when building the image
      - ./src/database/create_indicators_table.sql:/docker-entrypoint-initdb.d/create_indicators_table.sql
    networks:
      - dude_path_network

  dude_path_api:
    build: ./src/
    container_name: dude_path_app
    ports:
      - "23000:23000"
    environment:
      - POSTGRES_HOST=dude_path_database
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dude_path_network

