[tool.poetry]
name = "dude_path_poetry"
version = "0.1.0"
description = ""
authors = ["abjad <wasim.hajali@23degrees.io>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
